name: Continuous Integration
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
      - name: Install Packages
        run: npm install
      - name: Build Site
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: rdarida/simple-github-pages-deploy-action@v1
        with:
          git-base-folder: public
          commit-message: Auto build static site
