# This is a basic workflow to help you get started with Actions

name: Continuous Integration

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Set up node environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      # Install packages
      - name: Install Packages
        run: npm install
      
      # Build site
      - name: Build Site
        run: npm run build
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: rdarida/simple-github-pages-deploy-action@v1
        with:
          git-base-folder: public
          commit-message: Auto build static site
